###############################################################
#     ####         #                               #          # Jobuzzle - Copyright All rights reserved
#     ####         #                               #          #
#       ##  #####  ######  #     # ####### ####### #  #####   # @Author: revers
#       ## #     # #     # #     #      #       #  # #     #  #
#       ## #     # #     # #     #     #       #   # #     #  # @Date:   2015-08-08 11:12:48
#       ## #     # #     # #     #    #       #    # #     #  #
#       ## #     # #     # #     #   #       #     # ######   # @Last Modified by:   revers
#  ####### #     # #     # #     #  #       #      # #        #
#  ######   #####   ######  #####  ####### ####### # #######  # @Last Modified time: 2015-11-09 00:25:48
###############################################################

invokables : 
	navigation_loader_main_template : Loader/Template/NavigationLoaderMainTemplate
	navigation_error_404_template : Error/Template/NavigationError404Template
	navigation_popup_main_template: Popup/Template/NavigationPopupMainTemplate

shared : 
	navigation_error_404_template : true
	navigation_popup_main_template : true